name: Check and Increment Version

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: main-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: pr-branch

      - name: Compare package.json versions
        id: compare-versions
        run: |
          MAIN_VERSION=$(jq -r .version main-branch/package.json)
          PR_VERSION=$(jq -r .version pr-branch/package.json)
          echo "Main branch version: $MAIN_VERSION"
          echo "PR branch version: $PR_VERSION"
          
          if [ "$MAIN_VERSION" == "$PR_VERSION" ]; then
            IFS='.' read -r MAJOR MINOR PATCH <<< "$PR_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "New version: $NEW_VERSION"
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          else
            echo "Versions differ; no increment needed."
            echo "NO_UPDATE=true" >> $GITHUB_ENV
          fi

      - name: Update package.json if needed
        if: env.NO_UPDATE != 'true'
        run: |
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' pr-branch/package.json > temp.json && mv temp.json pr-branch/package.json

      - name: Commit and push changes
        if: env.NO_UPDATE != 'true'
        run: |
          cd pr-branch
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump package version to $NEW_VERSION"
          git push
